return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function () 
		local configs = require("nvim-treesitter.configs")

		configs.setup({
			ensure_installed = {
				"bash",
				"bibtex",
				"c",
				"c_sharp",
				"cmake",
				"comment",
				"cpp",
				"css",
				"csv",
				"diff",
				"dockerfile",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"go",
				"gomod",
				"gosum",
				"gotmpl",
				"gowork",
				"haskell",
				"hjson",
				"html",
				"htmldjango",
				"hyprlang",
				"java",
				"javascript",
				"json",
				"json5",
				"jsonc",
				"kotlin",
				"latex",
				"lua",
				"luadoc",
				"markdown",
				"markdown_inline",
				"ocaml",
				"python",
				"rust",
				"scss",
				"ssh_config",
				"toml",
				"typescript",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
			},
			sync_install = false,
			highlight = { enable = true },
			indent = { enable = true },  
		})
	end
}
