[env]
TERM = "xterm-256color"

[window]
padding = {x = 20, y = 20}
dynamic_padding = true
opacity = 0.75
blur = true

[scrolling]
multiplier = 5

# [font]
# normal = {family = "MesloLGM Nerd Font", style = "Bold"}
# bold = {family = "MesloLGM Nerd Font", style = "Bold"}
# italic = {family = "MesloLGM Nerd Font", style = "Italic"}
# bold_italic = {family = "MesloLGM Nerd Font", style = "Bold Italic"}

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Bold"}
bold = {family = "JetBrainsMono Nerd Font", style = "Bold"}
italic = {family = "JetBrainsMono Nerd Font", style = "Italic"}
bold_italic = {family = "JetBrainsMono Nerd Font", style = "Bold Italic"}

# Hyper-Snazzy theme (modified from NVCode Snazzy)
[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#97979b"

[colors.selection]
text =       "#282a36"
background = "#feffff"

[colors.primary]
background = "#1e2127"
foreground = "#eff0eb"

[colors.normal]
black =   "#282a36"
red =     "#ff5c57"
green =   "#5af78e"
yellow =  "#f3f99d"
blue =    "#57c7ff"
magenta = "#ff6ac1"
cyan =    "#9aedfe"
white =   "#f1f1f0"

[colors.bright]
black =   "#686868"
red =     "#ff5c57"
green =   "#5af78e"
yellow =  "#f3f99d"
blue =    "#57c7ff"
magenta = "#ff6ac1"
cyan =    "#9aedfe"
white =   "#eff0eb"

[cursor]
style = {shape = "Block", blinking = "On"}
blink_timeout = 0
